# Last Updated: Fri 01 Jun 2018 07:35:37 AM EDT
# Author: Anish Sevekari
# This zshrc is greatly inspired by oh-my-zsh

# Adding global variables and function path
ZSH=$HOME/dotfiles/zsh
fpath=($ZSH/functions $ZSH/completions $fpath)

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

if [ -f "~/.zsh_aliases" ]; then
	source ~/.zsh_aliases
fi

# import bash_aliases if it exist. Will stop using this if there are conflicts.
if [ -f "~/.bash_aliases" ]; then
	source ~/.bash_aliases
fi

# Theme
ZSH_THEME=agnoster

if [ ! "$ZSH_THEME" = "" ]; then
	if [ -f "$ZSH/themes/$ZSH_THEME.zsh-theme" ]; then
		source "$ZSH/themes/$ZSH_THEME.zsh-theme"
	elif [ -f "$ZSH/themes/$ZSH_THEME/$ZSH_THEME.zsh-theme" ]; then
		source "$ZSH/themes/$ZSH_THEME/$ZSH_THEME.zsh-theme"
	fi
fi
