# bash aliases
# Author: Anish Sevekari
# Last Updated: Tue 23 Jan 2018 11:47:17 PM EST

# common ssh targets
alias cmussh='ssh -p 2718 stranger@asevekarlaptop.math.cmu.edu'
alias booksync='unison /home/stranger/Documents/Books ssh://asevekarlaptop.math.cmu.edu:2718//home/stranger/Documents/Books'

alias cclip='xclip -selection clipboard'

